apiVersion: v1
kind: Namespace
metadata:
  name: development
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo
  namespace: development
  labels:
    app: todo
spec:
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: todo
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: todo
    spec:
      imagePullSecrets:
        - name: local
      containers:
        - name: todo
          image: example.com/todo:v1.0.0
          imagePullPolicy: Always
          ports:
            - containerPort: 80
              protocol: TCP
              name: 80tcp300001
---
apiVersion: v1
kind: Service
metadata:
  name: todo
  namespace: development
  labels:
    service: todo
spec:
  selector:
    app: todo
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30000
      protocol: TCP
  type: NodePort

